### ISSUE TITLE
I cannot reset 'repos' to single

### ISSUE THREAD

**Issue by simon-deprecated** [issue-sh/issue.sh#3]
<img width="129" alt="screenshot 2018-10-05 11 40 49" src="https://user-images.githubusercontent.com/35921747/46513467-92984300-c893-11e8-9aaf-40735a2ebdf6.png">

I want to use single repository for issue.sh.  After I test add more repos, I can't delete that.

**Comment by fnlctrl** [comment]
Hi Simon,

You can click on the "link" icon on the left of each repo name to remove it.
![image](https://user-images.githubusercontent.com/5557143/46572045-23654080-c9b2-11e8-8dd3-5c2871a2059b.png)

We'll make it clearer on the UI in the next release. Thanks for the feedback!

**Comment by fnlctrl** [comment]
Hi Simon,

In the latest release (v1.2.18) we have changed the icon to 
![image](https://user-images.githubusercontent.com/5557143/46747168-2e3a1100-cce3-11e8-9dab-074b74f24521.png)
Hope it clarifies its purpose.
