### ISSUE TITLE
Chromium Extension - paused before potential out-of-memory crash

### ISSUE THREAD

**Issue by disperate** [issue-sh/issue.sh#7]
Chromium stopped the extension on the Issue and Pull Request Tab with a `paused before potential out-of-memory crash` error.

The console log output is the following: [undefinedRepoName.log](https://github.com/issue-sh/issue.sh/files/2476905/undefinedRepoName.log)

issue.sh Version: 1.2.18
Chromium Version: 69.0.3497

A short test on Firefox yield the same result.

**Comment by fnlctrl** [comment]
Hi @disperate 
Thanks for the feedback!
It has been fixed in v1.2.19. Sorry for the inconvenience!
