### ISSUE TITLE
Rate limit -  Boards do not stop loading.

### ISSUE THREAD

**Issue by Kadaaran** [issue-sh/issue.sh#8]
Hey there 👋 

Keep getting ```Uncaught (in promise) Error: GetAccountInfo GET https://api.github.com/orgs/{my_organization}/members?per_page=100&role=admin: 403 API rate limit of 60 still exceeded until 2018-10-22 15:07:01 +0000 UTC, not making remote request. [rate reset in 6m38s]``` my `Boards` page keeps loading and I can't access it.

Any idea how I can fix it ? I have all the admin rights, do you think Issue might ask for too many requests at the same time and triggered the API rate limit ?

**Comment by Kadaaran** [comment]
Update: I got a 401, then I reloaded the page and now I get this: 
![screen shot 2018-10-22 at 17 20 20](https://user-images.githubusercontent.com/11220823/47301282-d83c6600-d61e-11e8-96c9-9a5aa218f4af.png)
Which is really weird because everything has been set up for a few weeks and worked fine until a few hours ago 🤔

**Comment by Kadaaran** [comment]
Update #2:  Also when I want to update the `Issue.sh` settings on my organization it never saves it and get back to `All repositories` even when I specify the rights to only one repo.

**Comment by fnlctrl** [comment]
Hi @Kadaaran 
Thanks for the feedback. This could be related to the recent GitHub service errors - I myself is still experiencing some random 404 pages, which I presume is happening on GitHub APIs.

**Comment by Kadaaran** [comment]
@fnlctrl That's it ! I just saw the status page a few minutes ago 🙈
